# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurtainsiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CurtainsiOS
  pod 'Alamofire', '~> 4.7'

  target 'CurtainsiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurtainsiOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
